version: 0.2

phases:
  install:
    runtime-versions:
      ruby: latest
  pre_build:
    commands:
      - gem install license_finder
      - license_finder permitted_licenses add "Apache 2.0"
      - license_finder permitted_licenses add "MIT"
  build:
    commands:
      - license_finder